name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'  # 只有當標籤符合此格式（如 v1.2.3）時才觸發

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet publish -c Release -r win-x64 --self-contained=false

    - name: Create zip package
      run: |
        cd ./bin/Release/net6.0-windows
        Compress-Archive * ../OBSNowPlayingOverlay_${{ github.ref_name }}.zip
      shell: pwsh

    - name: Generate Changelog
      id: changelog
      uses: mikepenz/release-changelog-builder-action@v3

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: ${{ github.ref_name }}
        draft: true
        body: ${{ steps.changelog.outputs.changelog }}

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./bin/Release/OBSNowPlayingOverlay_${{ github.ref_name }}.zip
        asset_name: OBSNowPlayingOverlay_${{ github.ref_name }}.zip
        asset_content_type: application/zip